### ISSUE TITLE
Sentry doesn't report panics which crash the process

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#109]
i.e https://github.com/matrix-org/sliding-sync/pull/108

We should, because crashes are bad and sentry worthy ;)

**Comment by DMRobertson** [comment]
E.g.

```
14:32:00 INF duration=14108.596573 p=3818 q=3819 r=0 size=403 status=200 u=@neutral:matrix.org
panic: assignment to entry in nil map

goroutine 251 [running]:
github.com/matrix-org/sliding-sync/sync3/caches.(*GlobalCache).OnNewEvent(0xc0029027e0, {0xc2a918, 0xc0038a9b90}, 0xc03068dba0)
	github.com/matrix-org/sliding-sync@v0.99.3-0.20230503103647-c9b41247e5fd/sync3/caches/global.go:280 +0xa4a
github.com/matrix-org/sliding-sync/sync3.(*Dispatcher).notifyListeners(0xc002902740, {0xc2a918, 0xc0038a9b90}, 0xc03068dba0, {0x0, 0x0, 0xc017d31a68?}, {0x0, 0x0}, 0x0, ...)
	github.com/matrix-org/sliding-sync@v0.99.3-0.20230503103647-c9b41247e5fd/sync3/dispatcher.go:256 +0x238
github.com/matrix-org/sliding-sync/sync3.(*Dispatcher).OnNewEvent(0xc002902740, {0xc2a918, 0xc0038a9b90}, {0xc03b369740?, 0xc03b369800?}, {0xc0428ef400?, 0x0?, 0x0?}, 0x0?)
	github.com/matrix-org/sliding-sync@v0.99.3-0.20230503103647-c9b41247e5fd/sync3/dispatcher.go:188 +0x487
github.com/matrix-org/sliding-sync/sync3/handler.(*SyncLiveHandler).Accumulate(0xc00ca24000, 0xc002529bc0)
	github.com/matrix-org/sliding-sync@v0.99.3-0.20230503103647-c9b41247e5fd/sync3/handler/handler.go:526 +0x2c7
github.com/matrix-org/sliding-sync/pubsub.(*V2Sub).onMessage(0xc002529bc0?, {0xc25540?, 0xc002529bc0?})
	github.com/matrix-org/sliding-sync@v0.99.3-0.20230503103647-c9b41247e5fd/pubsub/v2.go:137 +0x182
github.com/matrix-org/sync-v3/payloads.(*SerialisedListener).process(0xc000424600, {{0xffe908, 0x1}, {0xc000c5e840, 0xad, 0xb0}})
	github.com/matrix-org/sync-v3/payloads/dbnotify.go:283 +0x12c
github.com/matrix-org/sync-v3/payloads.(*DBListener).processNewPayloads(0xc000446140, {0xb25ac5, 0x4}, 0xc003cae010)
	github.com/matrix-org/sync-v3/payloads/dbnotify.go:111 +0x263
github.com/matrix-org/sync-v3/payloads.(*DBListener).ListenFrom(0xc000446140, {0xb25ac5, 0x4}, 0x35c3517, 0xa90f00?)
	github.com/matrix-org/sync-v3/payloads/dbnotify.go:139 +0x277
github.com/matrix-org/sync-v3/payloads.(*StartingPosListener).Listen(...)
	github.com/matrix-org/sync-v3/payloads/dbnotify.go:254
github.com/matrix-org/sync-v3/payloads.(*SerialisedListener).Listen(0xc000424600?, {0xb25ac5, 0x4}, 0xc0003cad80?)
	github.com/matrix-org/sync-v3/payloads/dbnotify.go:265 +0xb1
github.com/matrix-org/sliding-sync/pubsub.(*V2Sub).Listen(...)
	github.com/matrix-org/sliding-sync@v0.99.3-0.20230503103647-c9b41247e5fd/pubsub/v2.go:162
github.com/matrix-org/sliding-sync/sync3/handler.(*SyncLiveHandler).Listen.func1()
	github.com/matrix-org/sliding-sync@v0.99.3-0.20230503103647-c9b41247e5fd/sync3/handler/handler.go:113 +0x7c
created by github.com/matrix-org/sliding-sync/sync3/handler.(*SyncLiveHandler).Listen
	github.com/matrix-org/sliding-sync@v0.99.3-0.20230503103647-c9b41247e5fd/sync3/handler/handler.go:112 +0x56

```
