### ISSUE TITLE
Changing the number of lists breaks connection until restart

### ISSUE THREAD

**Issue by turt2live** [matrix-org/sliding-sync#18]
**Describe the bug**
```
2021/12/25 08:06:06 http: panic serving 172.26.0.4:45560: runtime error: index out of range [2] with length 2
goroutine 13816 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1802 +0xb9
panic({0x7bebe0, 0xc00012ca08})
        runtime/panic.go:1047 +0x266
github.com/matrix-org/sync-v3/sync3.(*SortableRoomLists).List(...)
        github.com/matrix-org/sync-v3/sync3/lists.go:11
github.com/matrix-org/sync-v3/sync3/handler.(*ConnState).onIncomingListRequest(0xc00041a800, 0x2, 0xc0004cf4f0, 0xc000147cd0)
        github.com/matrix-org/sync-v3/sync3/handler/connstate.go:225 +0xa05
github.com/matrix-org/sync-v3/sync3/handler.(*ConnState).onIncomingRequest(0xc00041a800, {0x870b00, 0xc0003a3b90}, 0xc0002a1720)
        github.com/matrix-org/sync-v3/sync3/handler/connstate.go:164 +0x3c9
github.com/matrix-org/sync-v3/sync3/handler.(*ConnState).OnIncomingRequest(0xc0003bd5c0, {0x870b00, 0xc0003a3b90}, {{0xc000368ff0, 0x40ebc7}, {0x30, 0x7c9540}}, 0xc000369001)
        github.com/matrix-org/sync-v3/sync3/handler/connstate.go:122 +0x65
github.com/matrix-org/sync-v3/sync3.(*Conn).OnIncomingRequest(0xc0004012c0, {0x870b00, 0xc0003a3b90}, 0xc0002a1720)
        github.com/matrix-org/sync-v3/sync3/conn.go:88 +0x310
github.com/matrix-org/sync-v3/sync3/handler.(*SyncLiveHandler).serve(0x400000c000278120, {0x7f618e367018, 0xc0003a7b00}, 0xc0001e5900)
        github.com/matrix-org/sync-v3/sync3/handler/handler.go:148 +0x734
github.com/matrix-org/sync-v3/sync3/handler.(*SyncLiveHandler).ServeHTTP(0x7b3740, {0x7f618e367018, 0xc0003a7b00}, 0x1c)
        github.com/matrix-org/sync-v3/sync3/handler/handler.go:91 +0x5b
github.com/matrix-org/sync-v3.allowCORS.func1({0x7f618e367018, 0xc0003a7b00}, 0xc0001e5900)
        github.com/matrix-org/sync-v3/v3.go:42 +0x299
net/http.HandlerFunc.ServeHTTP(0xc0001e5800, {0x7f618e367018, 0xc0003a7b00}, 0x12)
        net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001ee000, {0x7f618e367018, 0xc0003a7b00}, 0xc0001e5700)
        github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/zerolog/hlog.RemoteAddrHandler.func1.1({0x7f618e367018, 0xc0003a7b00}, 0xc0001e5700)
        github.com/rs/zerolog@v1.21.0/hlog/hlog.go:88 +0x159
net/http.HandlerFunc.ServeHTTP(0xc00029f440, {0x7f618e367018, 0xc0003a7b00}, 0x0)
        net/http/server.go:2047 +0x2f
github.com/rs/zerolog/hlog.AccessHandler.func1.1({0x86e5f0, 0xc0001fc380}, 0xc0002d1001)
        github.com/rs/zerolog@v1.21.0/hlog/hlog.go:201 +0x306
net/http.HandlerFunc.ServeHTTP(0xc0002d1080, {0x86e5f0, 0xc0001fc380}, 0xc0000a7870)
        net/http/server.go:2047 +0x2f
github.com/rs/zerolog/hlog.NewHandler.func1.1({0x86e5f0, 0xc0001fc380}, 0xc0001e5600)
        github.com/rs/zerolog@v1.21.0/hlog/hlog.go:30 +0x496
net/http.HandlerFunc.ServeHTTP(0x868100, {0x86e5f0, 0xc0001fc380}, 0xc000140b70)
        net/http/server.go:2047 +0x2f
github.com/matrix-org/sync-v3.(*server).ServeHTTP(0xc00011bf50, {0x86e5f0, 0xc0001fc380}, 0x10)
        github.com/matrix-org/sync-v3/v3.go:30 +0xb0
net/http.serverHandler.ServeHTTP({0x86d5d0}, {0x86e5f0, 0xc0001fc380}, 0xc0001e5600)
        net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0002a1680, {0x870b00, 0xc0001fa1b0})
        net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        net/http/server.go:3034 +0x4e8
Room: !XdNQQKxyQPITMAgdZJ:localhost - Sync v3 - 2021-12-25 00:46:38.064 +0000 UTC
```

**To Reproduce**
1. Set up a connection with 2 lists (no `session_id`)
2. Decide to start over, exclude `?pos=` and POST a whole new body with 3 lists
3. Receive error

To fix: restart the proxy

**Expected behavior**
It should start a new connection given the filtering changed dramatically.

**Comment by kegsay** [comment]
This should be fixed now.
