### ISSUE TITLE
Integration test flake: `TestPollerUpdatesRoomMemberTrackerOnGappySyncStateBlock`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/sliding-sync#234]
https://github.com/matrix-org/sliding-sync/actions/runs/5716475592/job/15488088788:

```
❌ TestPollerUpdatesRoomMemberTrackerOnGappySyncStateBlock (0s)
  panic: send on closed channel
  
  goroutine 20032 [running]:
  github.com/matrix-org/sliding-sync/pubsub.(*PubSub).Notify(0xc000080fe0, {0xbe2d20?, 0xc00185f880?}, {0xcffca0, 0xc0034aa480})
  	/home/runner/work/sliding-sync/sliding-sync/pubsub/pubsub.go:80 +0xd1
  github.com/matrix-org/sliding-sync/sync2/handler2.(*Handler).Accumulate(0xc000823000, {0xd05bd8, 0xc0016d7e00}, {0xc0001f311c, 0x10}, {0xc0001f313b, 0x41}, {0xc0016ed860, 0xc}, {0xc001b046a8, ...}, ...)
  	/home/runner/work/sliding-sync/sliding-sync/sync2/handler2/handler.go:323 +0xc47
  github.com/matrix-org/sliding-sync/sync2.(*PollerMap).Accumulate.func1()
  	/home/runner/work/sliding-sync/sliding-sync/sync2/poller.go:296 +0xce
  github.com/matrix-org/sliding-sync/sync2.(*PollerMap).execute(0x0?)
  	/home/runner/work/sliding-sync/sliding-sync/sync2/poller.go:285 +0x5b
  created by github.com/matrix-org/sliding-sync/sync2.(*PollerMap).EnsurePolling
  	/home/runner/work/sliding-sync/sliding-sync/sync2/poller.go:235 +0x16a
```

**Comment by kegsay** [comment]
On `2cc58cf28a8e9d60022fdd9c3203798432e53d15`
