### ISSUE TITLE
Failed to connect using PostgreSQL URI

### ISSUE THREAD

**Issue by melroy89** [matrix-org/sliding-sync#399]
Unable to use [PostgreSQL Connection URIs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS), errors on:

```sh
goroutine 1 [running]:
github.com/jmoiron/sqlx.MustExec(...)
	github.com/jmoiron/sqlx@v1.3.3/sqlx.go:722
github.com/jmoiron/sqlx.(*DB).MustExec(0xc000421988?, {0xdc5808?, 0xc000421988?}, {0x0?, 0xc000421901?, 0xc0004219d8?})
	github.com/jmoiron/sqlx@v1.3.3/sqlx.go:366 +0x46
github.com/matrix-org/sliding-sync/state.NewRoomsTable(...)
	github.com/matrix-org/sliding-sync/state/rooms_table.go:24
github.com/matrix-org/sliding-sync/state.NewStorageWithDB(0xc0005fc300, 0x8?)
	github.com/matrix-org/sliding-sync/state/storage.go:86 +0x38
github.com/matrix-org/sliding-sync.Setup({0xc00003e00e, 0x20}, {0xc00004200a, 0x76}, {0xc00004005e, 0x40}, {0x0, 0x0, 0x0, 0x3b9aca00, ...})
	github.com/matrix-org/sliding-sync/v3.go:117 +0x212
main.main()
	github.com/matrix-org/sliding-sync/cmd/syncv3/main.go:213 +0x175b
Sync v3 [0.99.15] (bbb886e)
Debug=false LogLevel= MaxConns=0
panic: parse "postgresql://synapse:secret@%2Fvar%2Flib%2Fpostgresql/syncv3": invalid URL escape "%2F"
```

While the PostgreSQL documentation clearly mentions this should be allowed:

> 
> The host part is interpreted as described for the parameter [host](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-HOST). In particular, a Unix-domain socket connection is chosen if the host part is either empty or looks like an absolute path name, otherwise a TCP/IP connection is initiated. Note, however, that the slash is a reserved character in the hierarchical part of the URI. So, to specify a non-standard Unix-domain socket directory, either omit the host part of the URI and specify the host as a named parameter, or percent-encode the path in the host part of the URI:
> 
> ```
> postgresql:///dbname?host=/var/lib/postgresql
> postgresql://%2Fvar%2Flib%2Fpostgresql/dbname
> ```

**Comment by spaetz** [comment]
Given this seems to be handled by https://github.com/lib/pq which describes itself as in maintenance mode and recommends the use of another package (https://github.com/jackc/pgx), I would not expect a speedy resolution.
