### ISSUE TITLE
pr8328 is exploding for me after about 10m of uptime

### ISSUE THREAD

**Issue by ara4n** [matrix-org/sliding-sync#42]
rageshake.ts:73 DELETE 1 6 ;
15:07:35.856 rageshake.ts:73 INSERT 1 3 !dLxrSBOoWMIiteVAfB:federator.dev ;
15:07:35.857 SlidingRoomListStore.ts:209 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'roomId')
    at SlidingRoomListStore.ts:209:25
    at Array.findIndex (<anonymous>)
    at SlidingRoomListStoreClass.refreshOrderedLists (SlidingRoomListStore.ts:208:58)
    at SlidingRoomListStoreClass.onSlidingSyncListUpdate (SlidingRoomListStore.ts:265:14)
    at SlidingSync.emit (events.js:153:1)
    at SlidingSync.emit (typed-event-emitter.ts:61:22)
    at sliding-sync.ts:882:22
    at Set.forEach (<anonymous>)
    at SlidingSync.start (sliding-sync.ts:881:36)
    at async SlidingSyncSdk.sync (sliding-sync-sdk.ts:721:9)

**Comment by kegsay** [comment]
Closing as fixed as the refactor for the list delta algorithm seems to have fixed it.
